name: Next cloud upload action
description: This action help to upload file to next cloud
author: 'Nghi Nguyen'
inputs:
  name:
    description: 'Name of the file to save'
    required: true
  uploadPath:
    description: 'Path of the folder upload file on next cloud'
    required: true
    default: ''
  filePath:
    description: 'Path of the file need to upload'
    required: true
  url:
    description: 'Next cloud url'
    required: true
  username:
    description: 'Next cloud username'
    required: true
  password:
    description: 'Next cloud password'
    required: true
outputs:
  share_url:
    description: 'Path of the folder upload file on next cloud'
    value: ${{ steps.uploadToNextCloud.outputs.shareUrl }}
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Upload file to next cloud
      id: uploadToNextCloud
      shell: bash
      run: |
        python $GITHUB_ACTION_PATH/scripts/upload_file.py --repo ${{ github.repository }} --name "${{ inputs.name }}" --uploadPath "${{ inputs.uploadPath }}" --filePath "${{ inputs.filePath }}" --url "${{ inputs.url }}" --username "${{ inputs.username }}" --password "${{ inputs.password }}"