name: Test Action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run action
        id: uploadFile
        uses: ./
        with:
          name: 'test.txt'
          uploadPath: ''
          filePath: 'test.txt'
          shareEnabled: 'true'
          url: ${{ secrets.NEXT_CLOUD_URL }}
          uploadPath: ${{ secrets.NEXT_CLOUD_UPLOAD_PATH }}
          username: ${{ secrets.NEXT_CLOUD_USERNAME }}
          password: ${{ secrets.NEXT_CLOUD_PASSWORD }}
      - name: Print output url
        run: echo "output_url=${{ steps.uploadFile.outputs.output_url }}"